from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# ==============================
# TRAINING DATA
# ==============================

stalking_sentences = [
    'someone is following me',
    'a man is following me',
    'a boy is following me',
    'someone keeps following me',
    'someone follows me every day',
    'someone follows me everywhere',
    'someone is stalking me',
    'a person is stalking me',
    'someone is watching me',
    'someone keeps watching me',
    'someone follows me when I leave college',
    'someone follows me from college',
    'someone follows me from work',
    'someone waits outside my college',
    'someone waits outside my house',
    'a man keeps waiting outside',
    'someone keeps coming near me',
    'someone follows me on the way home',
    'someone is following me on the road',
    'someone is following me at night',
    'someone keeps appearing near me',
    'someone follows me whenever I go outside',
    'someone waits for me near my college',
    'someone waits for me near my house',
    'someone keeps standing near my house',
    'someone keeps watching my movements',
    'someone follows me after college',
    'someone follows me after work',
    'someone follows me on my way home',
    'someone follows me to the bus stop',
    'someone follows me to the market',
    'someone follows me when I go shopping',
    'someone follows me whenever I leave home',
    'someone keeps coming to places where I go',
    'someone is always behind me',
    'someone keeps walking behind me',
    'someone keeps walking near me',
    'someone follows me whenever I travel',
    'someone follows me from the bus stop',
    'someone follows me from the metro station',
    'someone waits outside my workplace',
    'someone waits outside my hostel',
    'someone waits outside my apartment',
    'someone keeps coming outside my house',
    'someone is watching me from outside',
    'someone keeps staring at me and following me',
    'someone has been following me for days',
    'someone has been following me for weeks',
    'someone has followed me several times',
    'the same person keeps following me',
    'the same person follows me every day',
    'a stranger keeps following me',
    'a stranger follows me whenever I leave',
    'a person keeps following me after class',
    'a person follows me after college',
    'a person follows me on my way home',
    'someone follows me when I walk alone',
    'someone follows me whenever I am alone',
    'someone follows me at night',
    'someone follows me in the evening',
    'someone follows me in the morning',
    'someone follows me from the street',
    'someone follows me from the neighborhood',
    'someone keeps waiting for me outside',
    'someone keeps waiting near my college',
    'someone keeps waiting near my house',
    'someone keeps following me in public',
    'someone keeps following me on the road',
    'someone follows me wherever I go',
    'someone seems to know where I go',
    'someone keeps showing up wherever I am',
    'someone keeps appearing wherever I go',
    'someone follows me without saying anything',
    'someone follows me silently',
    'someone keeps walking behind me',
    'someone keeps watching me from a distance',
    'someone keeps looking at me and following me',
    'someone is following me home',
    'someone followed me home yesterday',
    'someone followed me home today',
    'someone has started following me',
    'someone keeps following me after work',
    'someone keeps following me after class',
    'someone follows me every time I leave college',
    'someone follows me every time I leave work',
    'someone follows me when I go outside',
    'someone follows me when I return home',
    'someone keeps waiting near my route',
    'someone keeps following the same route as me',
    'someone follows me on my daily route',
    'someone keeps coming behind me',
    'someone keeps walking behind me everywhere',
    'someone follows me when I take the bus',
    'someone follows me when I take the train',
    'ek ladka mera peecha kar raha hai',
    'woh mera peecha kar raha hai',
    'mujhe koi follow kar raha hai',
    'koi mera peecha kar raha hai',
    'koi roz mera peecha karta hai',
    'koi mere peeche aa raha hai',
    'ek aadmi mera peecha karta hai',
    'woh ladka roz mera peecha karta hai',
    'college se koi mera peecha kar raha hai',
    'ghar jaate waqt koi mera peecha karta hai',
    'koi mere ghar ke bahar wait karta hai',
    'koi mujhe follow kar raha hai',
    'koi mujhe roz follow karta hai',
    'koi mera roz peecha karta hai',
    'koi mere college ke bahar khada rehta hai',
    'koi mere ghar ke bahar khada rehta hai',
    'koi mera peecha karte hue ghar tak aata hai',
    'koi mere peeche peeche aa raha hai',
    'koi mujhe har jagah follow karta hai',
    'koi mujhe college se ghar tak follow karta hai',
    'ek aadmi mujhe follow kar raha hai',
    'ek ladka mujhe roz follow karta hai',
    'woh aadmi mere peeche aa raha hai',
    'mujhe koi roz dekh raha hai',
    'koi mujhe baar baar dekh raha hai',
    'koi meri movements dekh raha hai',
    'koi mere aas paas ghoomta rehta hai',
    'koi mere aas paas baar baar aata hai',
    'koi mere ghar ke paas wait karta hai',
    'koi college ke bahar mera wait karta hai',
    'koi mujhe raste mein follow karta hai',
    'koi mere saath saath chal raha hai',
    'koi mere peeche road par aa raha hai',
    'koi mujhe ghar jaate waqt follow karta hai',
    'koi mujhe kaafi din se follow kar raha hai',
    'koi mujhe kai dino se follow kar raha hai',
    'same aadmi mujhe roz follow karta hai',
    'same ladka baar baar mera peecha karta hai',
    'koi mujhe har baar bahar jaane par follow karta hai',
    'koi mujhe bus stop tak follow karta hai',
    'koi mujhe market tak follow karta hai',
    'koi mere hostel ke bahar khada rehta hai',
    'koi mere office ke bahar wait karta hai',
    'koi mere peeche chupke se aa raha hai',
    'koi door se mera peecha karta hai',
    'koi mujhe dekhte hue follow kar raha hai',
    'koi mere ghar ke aas paas ghoomta rehta hai',
    'koi mujhe har jagah follow karta hua lagta hai',
    'mujhe lagta hai koi mera peecha kar raha hai',
    'mujhe lagta hai koi mujhe follow kar raha hai',
    'koi baar baar mere aas paas aa raha hai',
    'koi roz mere raste mein milta hai',
    'koi mere daily route par follow karta hai',
    'koi mere college ke baad peecha karta hai',
    'koi mere kaam se ghar tak follow karta hai',
    'koi mujhe akela dekh kar follow karta hai',
    'koi raat ko mera peecha karta hai',
    'koi shaam ko mera peecha karta hai',
    'koi subah mera peecha karta hai',
    'koi mere ghar lautne par peecha karta hai',
    'koi mere peeche chal raha hai',
    'koi mujhe chupke se follow kar raha hai',
    'koi mujhe door se watch kar raha hai',
    'koi baar baar mere ghar ke paas aa raha hai',
    'koi mujhe dekh kar mere peeche aa jata hai',
    'koi meri location ka pata rakhta hai',
    'koi baar baar wahi jagah par aa jata hai jahan main hoti hoon',
    'koi mere har movement ko notice karta hai',
    'koi mujhe college mein follow karta hai',
    'koi mujhe office mein follow karta hai',
    'koi mujhe hostel tak follow karta hai',
    'koi mujhe bus mein follow karta hai',
    'koi mujhe train station tak follow karta haisomeone is threatening me through whatsapp',
]

online_threat_sentences = [
    'someone keeps threatening me online',
    'I keep receiving threats online',
    'someone is threatening me through instagram',
    'someone is threatening me through facebook',
    'someone is threatening me through social media',
    'someone is sending me threatening texts',
    'I received a threatening message',
    'I received threats from an unknown account',
    'someone keeps sending me threatening texts',
    'someone is threatening to upload my pictures',
    'someone is threatening to upload my videos',
    'someone is threatening to publish my photos',
    'someone is threatening to share my private pictures',
    'someone is threatening to share my private videos',
    'someone is threatening to make my photos public',
    'someone is threatening to expose my private information',
    'someone is using my photos to blackmail me',
    'someone is blackmailing me with private pictures',
    'someone is blackmailing me for money',
    'someone wants money or they will leak my photos',
    'someone wants money and is threatening me',
    'someone is demanding money and threatening me',
    'someone is threatening me if I refuse to pay',
    'someone is threatening to send my photos to others',
    'someone is threatening to send my pictures to my family',
    'someone is threatening to post my pictures online',
    'someone is threatening to upload my private video',
    'someone has my private pictures',
    'someone has my personal photos and is threatening me',
    'someone has my private information and is blackmailing me',
    'someone created a fake profile using my name',
    'someone created a fake account using my photos',
    'someone is using my photos without permission',
    'someone is threatening me from an unknown profile',
    'someone keeps contacting me from fake accounts',
    'someone keeps creating new accounts to contact me',
    'someone is harassing me through social media',
    'someone is sending me abusive messages online',
    'someone is sending me unwanted messages every day',
    'someone is threatening me through email',
    'someone is threatening me through text messages',
    'someone is threatening to reveal my private messages',
    'someone is threatening to expose our private conversation',
    'someone is threatening to share my personal information',
    'someone is threatening to leak my private content',
    'someone is blackmailing me online for money',
    'someone is forcing me to send money online',
    'someone is threatening me because I refused to send money',
    'someone is threatening me after I blocked them',
    'someone keeps threatening me from different accounts',
    'koi mujhe whatsapp par dhamki de raha hai',
    'koi mujhe instagram par dhamki de raha hai',
    'koi mujhe facebook par dhamki de raha hai',
    'koi mujhe social media par dhamki de raha hai',
    'koi mujhe online baar baar dhamki de raha hai',
    'koi mujhe threatening messages bhej raha hai',
    'mujhe online dhamki wale messages aa rahe hain',
    'mujhe ek unknown account se dhamki mil rahi hai',
    'koi meri photos upload karne ki dhamki de raha hai',
    'koi meri photos internet par daalne ki dhamki de raha hai',
    'koi meri video leak karne ki dhamki de raha hai',
    'koi meri private video share karne ki dhamki de raha hai',
    'koi meri personal information leak karne ki dhamki de raha hai',
    'koi meri private photos ke saath blackmail kar raha hai',
    'koi meri photos ke liye paise maang raha hai',
    'koi paise nahi dene par meri photo leak karne ki dhamki de raha hai',
    'koi mujhe paise ke liye blackmail kar raha hai',
    'koi meri photo mere family ko bhejne ki dhamki de raha hai',
    'koi meri private photo public karne ki dhamki de raha hai',
    'kisi ne meri photo se fake account banaya hai',
    'kisi ne meri photo se fake profile banayi hai',
    'koi meri photo bina permission ke use kar raha hai',
    'koi fake account se mujhe message kar raha hai',
    'koi baar baar naye account se mujhe contact kar raha hai',
    'koi mujhe social media par pareshan kar raha hai',
    'koi mujhe online abusive messages bhej raha hai',
    'koi mujhe roz unwanted messages bhej raha hai',
    'koi mujhe email par dhamki de raha hai',
    'koi mujhe text message mein dhamki de raha hai',
    'koi meri private chat share karne ki dhamki de raha hai',
    'koi meri personal information share karne ki dhamki de raha hai',
    'koi mujhe online blackmail kar raha hai',
    'koi mujhe online paise bhejne ke liye force kar raha hai',
    'maine paise dene se mana kiya toh woh mujhe dhamki de raha hai',
    'block karne ke baad bhi woh mujhe dhamki de raha hai',
    'koi mujhe alag alag accounts se dhamki de raha hai',
    'koi meri private pictures leak karne ki dhamki de raha hai',
    'koi meri video sabko bhejne ki dhamki de raha hai',
    'koi meri photos family ko bhejne ki dhamki de raha hai',
    'koi mujhe online expose karne ki dhamki de raha hai',
    'koi meri private information ke liye blackmail kar raha hai',
    'koi mujhe social media par blackmail kar raha hai',
    'koi mujhe fake profile se threaten kar raha hai',
    'koi mujhe online pareshan aur blackmail kar raha haimy husband is hurting me',
]

domestic_violence_sentences = [
    'my husband hits me',
    'my partner is beating me',
    'my boyfriend hits me',
    'someone at home is hurting me',
    'i am being abused at home',
    'my husband beats me',
    'my partner hurts me',
    'i am not safe at home',
    'someone in my family is hurting me',
    'ghar par mujhe maara ja raha hai',
    'mera husband mujhe maarta hai',
    'mera partner mujhe maarta hai',
    'ghar mein koi mujhe hurt kar raha hai',
    'ghar par main safe nahi hoon',
    'ghar par mujhe maar rahe hain',
    'mera pati mujhe maarta hai',
    'mera husband mujhe marta hai',
    'mera pati mujhe hurt karta hai',
    'ghar mein mujhe maara jaata hai',
    'ghar wale mujhe maarte hain',
    'mere ghar mein mujhe abuse kiya ja raha hai',
    'ghar par mere saath maar peet hoti hai',
    'mera partner mere saath maar peet karta hai',
    'mujhe ghar mein koi maar raha hai',
    'mere husband ne mujhe maara hai',
    'mere boyfriend ne mujhe maara hai',
    'ghar par mujhe torture kiya ja raha hai',
    'main ghar mein safe nahi hoon',
    'ghar mein mere saath violence ho rahi hai',
    'my husband is physically hurting me',
    'my husband keeps hitting me',
    'my husband hits me when he gets angry',
    'my husband has become violent with me',
    'my partner keeps hurting me',
    'my partner is physically abusive',
    'my boyfriend keeps hitting me',
    'my boyfriend is hurting me at home',
    'my partner keeps beating me',
    'my partner has hit me several times',
    'someone in my house keeps hitting me',
    'someone at home is physically hurting me',
    'someone in my family is beating me',
    'my family member keeps hurting me',
    'I am being physically abused at home',
    'I am being beaten at home',
    'I am afraid of someone at home',
    "I don't feel safe with my husband",
    "I don't feel safe with my partner",
    "I don't feel safe in my house",
    'my husband threatens me and hits me',
    'my partner threatens me at home',
    'my husband gets violent with me',
    'my partner gets violent when angry',
    'my boyfriend becomes violent with me',
    'someone at home is becoming violent',
    'someone at home keeps threatening me',
    'my husband has hurt me many times',
    'my partner has hurt me many times',
    'my boyfriend has hurt me before',
    'my husband pushed me',
    'my partner pushed me',
    'my boyfriend pushed me',
    'my husband slapped me',
    'my partner slapped me',
    'my boyfriend slapped me',
    'someone at home slapped me',
    'someone in my family hit me',
    'someone in my family keeps beating me',
    'my husband keeps abusing me',
    'my partner keeps abusing me',
    'I am scared of my husband',
    'I am scared of my partner',
    'I am scared to go home',
    'I am afraid to stay at home',
    "I don't feel safe around my husband",
    "I don't feel safe around my partner",
    'my husband is hurting me again',
    'my partner is hurting me again',
    'someone at home is hurting me again',
    'the violence at home is getting worse',
    'there is violence in my home',
    'there is physical violence at home',
    'I am experiencing violence at home',
    'my husband is physically abusive',
    'my partner is physically abusive',
    'my boyfriend is physically abusive',
    'my family is physically abusing me',
    'someone at home keeps attacking me',
    'someone at home keeps hitting me',
    'my husband keeps attacking me',
    'my partner keeps attacking me',
    'mera husband mujhe maarta hai',
    'mera pati mujhe maarta hai',
    'mera husband mujhe baar baar maarta hai',
    'mera pati mujhe baar baar maarta hai',
    'mera husband mere saath maar peet karta hai',
    'mera pati mere saath maar peet karta hai',
    'mera partner mujhe maarta hai',
    'mera partner mujhe baar baar maarta hai',
    'mera boyfriend mujhe maarta hai',
    'mera boyfriend mujhe hurt karta hai',
    'mera husband mujhe physically hurt karta hai',
    'mera partner mujhe physically hurt karta hai',
    'ghar mein koi mujhe maar raha hai',
    'ghar mein koi mujhe baar baar maar raha hai',
    'ghar par koi mujhe hurt kar raha hai',
    'ghar wale mujhe maarte hain',
    'mere ghar wale mujhe maarte hain',
    'mere family mein koi mujhe maarta hai',
    'mere ghar mein mere saath violence hoti hai',
    'ghar mein mere saath maar peet hoti hai',
    'ghar par mere saath maar peet ho rahi hai',
    'mujhe ghar par maara ja raha hai',
    'mujhe ghar mein maara ja raha hai',
    'main ghar par safe nahi hoon',
    'main ghar mein safe nahi hoon',
    'mujhe apne husband se dar lagta hai',
    'mujhe apne pati se dar lagta hai',
    'mujhe apne partner se dar lagta hai',
    'mujhe ghar jaane se dar lagta hai',
    'mera husband gussa karke mujhe maarta hai',
    'mera partner gusse mein mujhe maarta hai',
    'mera boyfriend gusse mein mujhe maarta hai',
    'mera husband mujhe thappad maarta hai',
    'mera partner mujhe thappad maarta hai',
    'mere pati ne mujhe thappad maara',
    'mere husband ne mujhe maara',
    'mere pati ne mujhe maara',
    'mere partner ne mujhe maara',
    'mere boyfriend ne mujhe maara',
    'ghar mein kisi ne mujhe maara',
    'ghar wale mujhe physically hurt karte hain',
    'koi ghar mein mujhe baar baar hurt karta hai',
    'mere husband ne mujhe push kiya',
    'mere partner ne mujhe push kiya',
    'mere boyfriend ne mujhe push kiya',
    'mera husband mujhe dhamki bhi deta hai aur maarta bhi hai',
    'mera partner mujhe dhamki deta hai',
    'ghar mein violence badh rahi hai',
    'mere ghar mein violence ho rahi hai',
    'mere ghar mein physical violence ho rahi hai',
    'main ghar mein violence face kar rahi hoon',
    'mere husband ka behaviour violent ho gaya hai',
    'mera partner violent ho gaya hai',
    'mera husband mujhe abuse karta hai',
    'mera partner mujhe abuse karta hai',
    'mera pati mujhe abuse karta hai',
    'ghar par mujhe abuse kiya ja raha hai',
    'ghar mein mujhe torture kiya ja raha hai',
    'ghar mein koi mujhe attack karta hai',
    'mera husband mujhe baar baar hurt karta hai',
    'mera partner mujhe baar baar hurt karta hai',
    'mere boyfriend ne mujhe pehle bhi maara hai',
    'mera husband mujhe dobara maar raha hai',
    'mera partner mujhe dobara hurt kar raha hai',
    'ghar mein koi mujhe dobara maar raha hai',
    'mujhe ghar mein kisi se safe feel nahi hota',
    'mujhe ghar par kisi se dar lagta hai',
]

harassment_sentences = [
    'someone is harassing me',
    'I am being harassed',
    'someone keeps bothering me',
    'someone is bothering me at college',
    'someone is harassing me at college',
    'someone is harassing me at work',
    'a person keeps making me uncomfortable',
    'someone keeps disturbing me',
    'I am facing harassment',
    'a boy is bothering me',
    'someone keeps calling me',
    'someone keeps messaging me',
    'someone is bothering me repeatedly',
    'someone makes me uncomfortable every day',
    'someone keeps making unwanted comments',
    'someone keeps passing unwanted comments',
    'someone is troubling me',
    'someone keeps troubling me',
    'I feel uncomfortable because of someone',
    'college mein koi mujhe pareshan kar raha hai',
    'koi mujhe pareshan kar raha hai',
    'mujhe harass kiya ja raha hai',
    'koi baar baar mujhe disturb kar raha hai',
    'college mein koi mujhe harass kar raha hai',
    'koi mujhe baar baar call kar raha hai',
    'koi mujhe baar baar message kar raha hai',
    'koi mujhe roz pareshan karta hai',
    'koi mujhe bahut disturb kar raha hai',
    'koi mujhe unwanted messages bhej raha hai',
    'someone keeps bothering me',
    'someone keeps disturbing me',
    'someone keeps annoying me',
    'someone keeps making me uncomfortable',
    'someone makes me uncomfortable at college',
    'someone makes me uncomfortable at work',
    'someone keeps bothering me at college',
    'someone keeps bothering me at work',
    'someone keeps calling me repeatedly',
    'someone keeps sending me messages',
    'someone keeps texting me without stopping',
    'someone keeps making unwanted comments',
    'someone keeps making inappropriate comments',
    'someone keeps saying uncomfortable things to me',
    'someone keeps making me feel uncomfortable',
    'someone keeps disturbing me during class',
    'someone keeps bothering me after class',
    'someone keeps bothering me on campus',
    'someone keeps troubling me at college',
    'someone keeps troubling me at work',
    'someone keeps following me around college',
    'someone keeps coming near me at college',
    'someone keeps coming to my workplace',
    'someone keeps trying to talk to me even when I say no',
    'someone does not respect my boundaries',
    'someone keeps contacting me after I asked them to stop',
    'someone keeps calling after I asked them not to',
    'someone keeps messaging after I asked them to stop',
    'someone keeps sending unwanted texts',
    'someone keeps sending unwanted messages',
    'someone keeps making unwanted jokes about me',
    'someone keeps making inappropriate jokes',
    'someone keeps commenting on my appearance',
    'someone keeps making comments about my body',
    'someone keeps making me uncomfortable in public',
    'someone keeps bothering me on the bus',
    'someone keeps bothering me on the train',
    'someone keeps bothering me near college',
    'someone keeps bothering me near my house',
    'someone keeps disturbing me every day',
    'someone has been bothering me for days',
    'someone has been harassing me for weeks',
    'I am facing repeated harassment',
    'I keep getting unwanted calls',
    'I keep receiving unwanted messages',
    'I keep receiving unwanted comments',
    'I feel uncomfortable because someone keeps bothering me',
    'I feel unsafe because someone keeps harassing me',
    'someone is repeatedly disturbing me',
    'someone is repeatedly bothering me',
    'someone is repeatedly contacting me',
    'someone keeps trying to get my attention',
    'someone keeps insulting me',
    'someone keeps making rude comments to me',
    'someone keeps making inappropriate remarks',
    'someone keeps embarrassing me in public',
    'someone keeps humiliating me',
    'someone keeps teasing me even after I say stop',
    'someone keeps bothering me despite saying no',
    'someone refuses to leave me alone',
    'someone will not stop contacting me',
    'someone keeps coming back after I tell them to stop',
    'koi mujhe baar baar pareshan kar raha hai',
    'koi mujhe baar baar disturb kar raha hai',
    'koi mujhe baar baar tang kar raha hai',
    'koi mujhe roz pareshan karta hai',
    'koi mujhe college mein pareshan karta hai',
    'koi mujhe college mein harass karta hai',
    'koi mujhe class mein disturb karta hai',
    'koi mujhe class ke baad pareshan karta hai',
    'koi mujhe workplace par pareshan karta hai',
    'koi mujhe baar baar call karta hai',
    'koi mujhe baar baar message karta hai',
    'koi mujhe unwanted messages bhejta hai',
    'koi mujhe baar baar unwanted call karta hai',
    'koi mujhe baar baar comment karta hai',
    'koi mere baare mein unwanted comments karta hai',
    'koi mere looks par baar baar comment karta hai',
    'koi mere body par comment karta hai',
    'koi mujhe uncomfortable feel karata hai',
    'koi mujhe baar baar uncomfortable karta hai',
    'koi meri boundaries respect nahi karta',
    'koi mere mana karne ke baad bhi contact karta hai',
    'mana karne ke baad bhi koi mujhe message karta hai',
    'mana karne ke baad bhi koi mujhe call karta hai',
    'koi mujhe baar baar tang karta hai',
    'koi mujhe roz disturb karta hai',
    'koi mujhe college mein roz pareshan karta hai',
    'koi mujhe office mein pareshan karta hai',
    'koi mere aas paas baar baar aata hai',
    'koi mujhe baar baar unwanted baatein bolta hai',
    'koi mere saath badtameezi karta hai',
    'koi mujhe baar baar insult karta hai',
    'koi mujhe sabke saamne embarrass karta hai',
    'koi mujhe baar baar tease karta hai',
    'koi mujhe stop bolne ke baad bhi tease karta hai',
    'koi mujhe akela nahi chhodta',
    'koi baar baar mere peeche pad raha hai',
    'koi mujhe baar baar contact kar raha hai',
    'koi mujhe baar baar disturb kar raha hai',
    'koi mujhe public place mein pareshan karta hai',
    'koi bus mein mujhe pareshan karta hai',
    'koi train mein mujhe pareshan karta hai',
    'koi college ke paas mujhe pareshan karta hai',
    'koi mere ghar ke paas mujhe pareshan karta hai',
    'koi mujhe kai dino se pareshan kar raha hai',
    'koi mujhe kai hafton se harass kar raha hai',
    'mujhe baar baar harassment face karna pad raha hai',
    'mujhe unwanted calls aa rahe hain',
    'mujhe unwanted messages aa rahe hain',
    'mujhe unwanted comments mil rahe hain',
    'koi baar baar mujhe contact karne ki koshish karta hai',
    'koi mujhe baar baar rude baatein bolta hai',
    'koi mere saath inappropriate baatein karta hai',
    'koi mujhe sabke saamne insult karta hai',
    'koi mujhe baar baar uncomfortable feel karata hai',
    'koi mujhe mana karne ke baad bhi pareshan karta hai',
    'koi mujhe akela nahi chhod raha hai',
    'koi baar baar mere paas aa raha hai',
    'koi baar baar mujhe disturb kar raha hai',
    "I am being harassed",
"someone is harassing me",
"someone keeps harassing me",
"I am being harassed online",
"someone is harassing me online",
"someone keeps bothering me online",
"someone is repeatedly bothering me",
"someone keeps making me uncomfortable",
"someone keeps disturbing me",
"someone is bothering me on social media",
"someone keeps sending me unwanted messages",
"someone keeps commenting on my posts",
"someone is making unwanted comments online",
"someone keeps contacting me even after I asked them to stop",
"someone keeps messaging me even though I don't want them to",
"someone is repeatedly disturbing me online",
"I feel uncomfortable because someone keeps contacting me",
"someone keeps targeting me online",
"someone keeps bothering me through social media",
"I am receiving unwanted messages",

"koi mujhe pareshan kar raha hai",
"koi mujhe baar baar pareshan karta hai",
"koi mujhe online pareshan kar raha hai",
"koi mujhe social media par pareshan karta hai",
"koi mujhe baar baar message karta hai",
"koi mujhe unwanted messages bhej raha hai",
"koi mujhe online baar baar contact karta hai",
"koi mujhe uncomfortable feel karata hai",
"koi mujhe baar baar disturb karta hai",
"koi mujhe social media par disturb karta hai",
"koi mujhe online tang kar raha hai",
"koi mujhe baar baar tang karta hai",
"koi meri posts par unwanted comments karta hai",
"koi mujhe message karke pareshan karta hai",
"someone is harassing me online",

]

physical_danger_sentences = [
    'someone is trying to attack me',
    'someone is trying to hurt me',
    'I think someone will attack me',
    'someone has a weapon',
    'someone is trying to hit me',
    'someone is threatening to attack me',
    'I am scared someone will hurt me',
    'someone is coming after me',
    'someone is trying to beat me',
    'someone is chasing me',
    'someone is trying to catch me',
    'someone is threatening to hurt me',
    'someone is standing outside and threatening me',
    'someone is trying to harm me',
    'someone is following me and threatening me',
    'mujhe koi attack karne wala hai',
    'koi mujhe maarne aa raha hai',
    'koi mujhe hurt karne wala hai',
    'koi mujhe maarne ki koshish kar raha hai',
    'koi mujhe nuksan pahunchane wala hai',
    'koi mujhe dhamki de raha hai ki maar dega',
    'someone is trying to hurt me',
    'someone is trying to attack me',
    'someone is trying to hit me',
    'someone is trying to beat me',
    'someone wants to hurt me',
    'someone wants to attack me',
    'someone is coming to hurt me',
    'someone is coming to attack me',
    'someone is chasing me',
    'someone is running after me',
    'someone is following me and trying to hurt me',
    'someone is following me and threatening me',
    'someone is threatening to hit me',
    'someone is threatening to beat me',
    'someone is threatening to kill me',
    'someone is threatening my life',
    'I think I am in danger',
    'I think someone will hurt me',
    'I think someone is going to attack me',
    'I am afraid someone will attack me',
    'I am afraid someone will hurt me',
    'I am scared for my life',
    'I am scared for my safety',
    "I don't feel safe right now",
    "I don't feel safe outside",
    "I don't feel safe where I am",
    'I need help immediately',
    'I need help right now',
    'I need immediate help',
    'someone has a knife',
    'someone has a gun',
    'someone has a weapon',
    'someone is carrying a weapon',
    'someone is holding a knife',
    'someone is holding a weapon',
    'someone is attacking me',
    'someone is physically attacking me',
    'someone is trying to harm me',
    'someone is trying to injure me',
    'someone is trying to chase me',
    'someone is blocking my way',
    'someone is preventing me from leaving',
    'someone is standing outside and threatening me',
    'someone is waiting outside to hurt me',
    'someone is threatening me in person',
    'someone is threatening me face to face',
    'someone is trying to force me somewhere',
    'someone is forcing me to go with them',
    'someone is trying to grab me',
    'someone is trying to catch me',
    'someone is trying to physically hurt me',
    'koi mujhe maarne ki koshish kar raha hai',
    'koi mujhe hurt karne ki koshish kar raha hai',
    'koi mujhe attack karne ki koshish kar raha hai',
    'koi mujhe nuksan pahunchane ki koshish kar raha hai',
    'koi mujhe maarne aa raha hai',
    'koi mujhe hurt karne aa raha hai',
    'koi mujhe attack karne aa raha hai',
    'koi mere peeche bhaag raha hai',
    'koi mera peecha karke mujhe hurt karna chahta hai',
    'koi mujhe maarne ki dhamki de raha hai',
    'koi mujhe attack karne ki dhamki de raha hai',
    'koi mujhe jaan se maarne ki dhamki de raha hai',
    'koi meri jaan ko khatra de raha hai',
    'mujhe apni jaan ka darr hai',
    'mujhe apni safety ka darr hai',
    'mujhe lagta hai main danger mein hoon',
    'mujhe lagta hai koi mujhe maar dega',
    'mujhe lagta hai koi mujh par attack karega',
    'mujhe dar hai koi mujhe hurt karega',
    'main abhi safe nahi hoon',
    'main bahar safe nahi hoon',
    'main yahan safe nahi hoon',
    'mujhe abhi turant help chahiye',
    'mujhe turant madad chahiye',
    'mujhe abhi madad ki zarurat hai',
    'kisi ke paas chaku hai',
    'kisi ke paas weapon hai',
    'koi weapon lekar aa raha hai',
    'koi chaku lekar mujhe maarne aa raha hai',
    'koi mujhe chaku se maarne ki dhamki de raha hai',
    'koi mujhe physically hurt kar raha hai',
    'koi mujhe physically attack kar raha hai',
    'koi mujhe maar raha hai',
    'koi mujhe peetne ki koshish kar raha hai',
    'koi mujhe pakadne ki koshish kar raha hai',
    'koi mujhe zabardasti le jaane ki koshish kar raha hai',
    'koi mujhe zabardasti kahin le jaana chahta hai',
    'koi mujhe pakadne aa raha hai',
    'koi mera raasta rok raha hai',
    'koi mujhe bahar jaane nahi de raha',
    'koi bahar khada hokar mujhe dhamki de raha hai',
    'koi mujhe saamne se dhamki de raha hai',
    'koi mujhe force kar raha hai',
    'koi mujhe physically harm karna chahta hai',
    'koi mujhe nuksan pahunchana chahta hai',
    'koi mujhe pakadne aur hurt karne ki koshish kar raha hai',
    "I am being harassed",
"someone is harassing me",
"someone keeps harassing me",
"I am being harassed online",
"someone is harassing me online",
"someone keeps bothering me online",
"someone is repeatedly bothering me",
"someone keeps sending me unwanted messages",
"someone is making unwanted comments about me online",
"someone keeps disturbing me on social media",
"someone is repeatedly making me uncomfortable online",
"koi mujhe online pareshan kar raha hai",
"koi mujhe social media par pareshan karta hai",


]

emergency_help_sentences = [
    'please save me',
    'save me',
    'save me please',
    'someone is attacking me with knife',
    'someone is attacking me',
    'someone has a knife',
    'someone is attacking me with a weapon',
    'attack',
    'attacking me',
    'hamla',
    'hamla ho raha hai',
    'mujh par hamla ho raha hai',
    'chaku',
    'kisi ke paas chaku hai',
    'koi mujhe chaku se maar raha hai',
    'bachao',
    'bachaoo',
    'bachaooo',
    'bachaoooo',
    'bachaao',
    'bachaaoo',
    'mujhe bachao',
    'mujhe bachaoo',
    'mujhe bachao please',
    'please mujhe bachao',
    'koi bachao',
    'koi mujhe bachao',
    'mujhe bacha lo',
    'please mujhe bacha lo',
    'i am scared please help',
    'i need help now',
    'please help me now',
    'help me now',
    'someone please help',
    'please help me immediately',
    'please help me right now',
    'someone please help me now',
    'help me please',
    'please someone help me',
    'somebody please help me',
    'can somebody help me',
    'can anyone help me',
    'can anyone hear me',
    'please save me',
    'please come and help me',
    'I need help immediately',
    'I need someone to help me',
    'I need emergency help',
    'I need urgent help',
    'I am in an emergency',
    'this is an emergency',
    'there is an emergency',
    'I am in immediate danger',
    'I am in serious danger',
    'I need help urgently',
    'please call the police',
    'please call emergency services',
    'call the police please',
    'call 112 please',
    'please call 112',
    'help me call 112',
    'I need emergency services',
    'someone please call for help',
    'please get help for me',
    'please send help',
    'send help please',
    'help me someone',
    'help me please someone',
    'I am scared please help me',
    'I am afraid please help me',
    'I am trapped please help me',
    'I cannot get out please help me',
    'I cannot leave please help me',
    'someone is attacking me right now',
    'someone is hurting me right now',
    'someone is trying to hurt me right now',
    'someone is chasing me right now',
    'someone is threatening me right now',
    'I am being attacked',
    'I am being hurt',
    'I am being threatened',
    'I need help right away',
    'please help me before something happens',
    'please help me I am not safe',
    'mujhe abhi bachao',
    'mujhe turant bachao',
    'please mujhe abhi bachao',
    'please mujhe turant bachao',
    'koi mujhe abhi bachao',
    'koi mujhe turant bachao',
    'koi please meri help karo',
    'please meri help karo abhi',
    'mujhe abhi help chahiye',
    'mujhe turant help chahiye',
    'mujhe emergency help chahiye',
    'mujhe jaldi madad chahiye',
    'meri jaan ko khatra hai',
    'meri jaan khatre mein hai',
    'main bahut danger mein hoon',
    'main abhi danger mein hoon',
    'main emergency mein hoon',
    'ye emergency hai',
    'please 112 par call karo',
    'koi 112 par call karo',
    'police ko call karo',
    'please police ko call karo',
    'mere liye help bulao',
    'mere liye police bulao',
    'koi mere liye madad bulao',
    'please mere liye help bulao',
    'mujhe abhi bachao please',
    'mujhe turant bachao please',
    'main phas gayi hoon',
    'main phas gaya hoon',
    'main bahar nahi nikal pa rahi hoon',
    'main bahar nahi nikal pa raha hoon',
    'mujhe koi attack kar raha hai',
    'mujh par abhi attack ho raha hai',
    'koi mujhe abhi maar raha hai',
    'koi mujhe abhi hurt kar raha hai',
    'koi mujhe abhi dhamki de raha hai',
    'koi mera peecha kar raha hai abhi',
    'mujhe abhi danger hai',
    'mujhe abhi khatra hai',
    'please meri jaan bachao',
    'koi meri jaan bachao',
    'mujhe jaldi bachao',
    'mujhe abhi madad karo',
    'please abhi meri madad karo',
    'koi meri help karo abhi',
    'mujhe emergency mein help chahiye',
    'please mere liye 112 call karo',
]

general_support_sentences = [
    'help',
    'help me',
    'help please',
    'please help',
    'please help me',
    'helpp',
    'helppp',
    'helpppp',
    'plz help',
    'plzz help',
    'pls help',
    'plss help',
    'someone help me',
    'somebody help me',
    'can someone help me',
    'I need help',
    'I am scared',
    "I don't feel safe",
    'I am worried',
    'I am afraid',
    'I need safety help',
    'what should I do',
    "I don't know what to do",
    'I feel unsafe',
    'I need some advice',
    'I need support',
    'please tell me what to do',
    'I want help',
    'I need someone to talk to',
    'I am feeling scared',
    'I am feeling worried',
    'I need guidance',
    'can you help me',
    'I am in danger',
    'mujhe help chahiye',
    'please meri help karo',
    'mujhe dar lag raha hai',
    'main safe nahi hoon',
    'mujhe samajh nahi aa raha kya karu',
    'mujhe kuch samajh nahi aa raha',
    'mujhe madad chahiye',
    'please meri madad karo',
    'mujhe advice chahiye',
    'mujhe kya karna chahiye',
    'meri help karo',
    'meri madad karo',
    'mujhe abhi help chahiyeI need someone to help me',
    'I need someone to guide me',
    'I need some guidance',
    'I need some support',
    'I need emotional support',
    'I need advice',
    'I need some advice',
    'can you give me advice',
    'can you guide me',
    'please guide me',
    'please advise me',
    'what can I do',
    'what should I do now',
    'what can I do now',
    'please tell me what to do',
    "I don't know what to do",
    'I am confused',
    "I don't know how to handle this",
    "I don't know how to deal with this",
    'I need help dealing with this',
    'I need help with this situation',
    'can you help me with this',
    'can someone guide me',
    'can someone advise me',
    'I want to talk to someone',
    'I need someone to talk to',
    'I need somebody to talk to',
    'I just want some support',
    'I want some guidance',
    'I want to know what I should do',
    'please tell me what I can do',
    'how can I stay safe',
    'how can I protect myself',
    'what should I do to stay safe',
    'how can I get help',
    'where can I get help',
    'who can help me',
    'who should I contact',
    'who can I contact for help',
    'I need safety advice',
    'I need safety guidance',
    'I want safety information',
    'I have a safety concern',
    'I have a problem',
    'I am facing a problem',
    'I am worried about my safety',
    'I am concerned about my safety',
    'I feel nervous',
    'I feel frightened',
    'I feel uncomfortable',
    'I feel unsafe',
    "I don't feel comfortable",
    'I am scared',
    'I am afraid',
    'I am worried',
    'I am feeling nervous',
    'I am feeling afraid',
    'I am feeling unsafe',
    "I don't know who to contact",
    'mujhe kisi ki help chahiye',
    'mujhe kisi se baat karni hai',
    'mujhe kisi se baat karni hai please',
    'mujhe guidance chahiye',
    'mujhe support chahiye',
    'mujhe advice chahiye',
    'mujhe salah chahiye',
    'mujhe kuch advice do',
    'mujhe guide karo',
    'please mujhe guide karo',
    'mujhe kya karna chahiye ab',
    'main kya karu',
    'main ab kya karu',
    'mujhe samajh nahi aa raha',
    'mujhe nahi pata kya karu',
    'mujhe samajh nahi aa raha kya karna hai',
    'mujhe samajh nahi aa raha kaise handle karu',
    'mujhe is situation mein help chahiye',
    'mujhe is problem mein help chahiye',
    'kya aap meri help kar sakte ho',
    'kya koi meri help kar sakta hai',
    'kya koi mujhe guide kar sakta hai',
    'mujhe kisi se baat karni hai',
    'mujhe kisi se salah leni hai',
    'mujhe support ki zarurat hai',
    'mujhe safety advice chahiye',
    'mujhe safety ke baare mein jaana hai',
    'main safe kaise rahu',
    'main apne aap ko kaise safe rakhu',
    'mujhe kaise safe rehna chahiye',
    'mujhe help kahan milegi',
    'mujhe madad kahan milegi',
    'meri help kaun kar sakta hai',
    'mujhe kis se contact karna chahiye',
    'mujhe kiski madad leni chahiye',
    'mujhe apni safety ki chinta hai',
    'mujhe apni safety ko lekar darr hai',
    'mujhe tension ho rahi hai',
    'mujhe dar lag raha hai',
    'main pareshan hoon',
    'main bahut worried hoon',
    'main nervous hoon',
    'main uncomfortable feel kar rahi hoon',
    'main uncomfortable feel kar raha hoon',
    'main safe feel nahi kar rahi hoon',
    'main safe feel nahi kar raha hoon',
    'mujhe kuch samajh nahi aa raha kya karu',
    'please mujhe batao kya karna hai',
    'please mujhe batao main kya karu',
]


training_sentences = (
    stalking_sentences
    + online_threat_sentences
    + domestic_violence_sentences
    + harassment_sentences
    + physical_danger_sentences
    + emergency_help_sentences
    + general_support_sentences
)

training_labels = (
    ["stalking"] * len(stalking_sentences)
    + ["online_threat"] * len(online_threat_sentences)
    + ["domestic_violence"] * len(domestic_violence_sentences)
    + ["harassment"] * len(harassment_sentences)
    + ["physical_danger"] * len(physical_danger_sentences)
    + ["emergency_help"] * len(emergency_help_sentences)
    + ["general_support"] * len(general_support_sentences)
)

print("Training sentences:", len(training_sentences))
print("Training labels:", len(training_labels))

if len(training_sentences) != len(training_labels):
    raise ValueError(
        f"Dataset mismatch! "
        f"Sentences={len(training_sentences)}, "
        f"Labels={len(training_labels)}"
    )

print("✅ Dataset is balanced!")

# ==============================
# TRAIN AI MODEL
# ==============================

vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2)
)

X = vectorizer.fit_transform(training_sentences)

model = LogisticRegression(max_iter=1000)

model.fit(X, training_labels)

# -------- MODEL EVALUATION --------

training_predictions = model.predict(X)

accuracy = accuracy_score(training_labels, training_predictions)

print("\n========== MODEL EVALUATION ==========")
print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(training_labels, training_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(training_labels, training_predictions))

# ==============================
# TEST DATASET
# ==============================

test_sentences = [
    # STALKING
    "a person keeps following me on my way home",
    "someone is watching me wherever I go",
    "a stranger waits for me outside college",
    "koi roz mera peecha karta hai",

    # ONLINE THREAT
    "someone is threatening to upload my private pictures",
    "a person is blackmailing me through social media",
    "someone sent me threatening messages on whatsapp",
    "koi meri private photos leak karne ki dhamki de raha hai",

    # DOMESTIC VIOLENCE
    "my husband physically hurts me at home",
    "my family member beats me",
    "my partner is violent with me at home",
    "ghar mein mera pati mujhe maarta hai",

    # HARASSMENT
    "a person keeps making unwanted comments about me",
    "someone repeatedly makes me uncomfortable",
    "a boy keeps disturbing me at college",
    "koi mujhe college mein baar baar pareshan karta hai",

    # PHYSICAL DANGER
    "someone is coming towards me to hurt me",
    "a person is threatening to physically harm me",
    "someone is chasing me and I am scared",
    "koi mujhe maarne ki dhamki de raha hai",

    # EMERGENCY HELP
    "please rescue me right now",
    "someone is attacking me right now",
    "I need immediate help",
    "mujhe abhi bachao",

    # GENERAL SUPPORT
    "I need advice about a safety problem",
    "I am worried and don't know what to do",
    "please guide me about my situation",
    "mujhe samajh nahi aa raha kya karun"
]

test_labels = [
    "stalking",
    "stalking",
    "stalking",
    "stalking",

    "online_threat",
    "online_threat",
    "online_threat",
    "online_threat",

    "domestic_violence",
    "domestic_violence",
    "domestic_violence",
    "domestic_violence",

    "harassment",
    "harassment",
    "harassment",
    "harassment",

    "physical_danger",
    "physical_danger",
    "physical_danger",
    "physical_danger",

    "emergency_help",
    "emergency_help",
    "emergency_help",
    "emergency_help",

    "general_support",
    "general_support",
    "general_support",
    "general_support"
]


# ==============================
# TEST DATASET EVALUATION
# ==============================

X_test = vectorizer.transform(test_sentences)

test_predictions = model.predict(X_test)

test_accuracy = accuracy_score(test_labels, test_predictions)

print("\n========== TEST DATASET EVALUATION ==========")
print("Test Accuracy:", test_accuracy)

print("\nTest Classification Report:")
print(classification_report(test_labels, test_predictions))

print("\nTest Confusion Matrix:")
print(confusion_matrix(test_labels, test_predictions))




# ==============================
# SIMPLE RESPONSES
# ==============================

responses = {

    "stalking": {
        "risk": "High",
        "message": "Someone may be following or stalking you. Move to a safe and crowded place and avoid going somewhere isolated. Call someone you trust and share your location if possible. If you are in immediate danger, call 112."
    },

    "online_threat": {
        "risk": "Medium",
        "message": "Someone is threatening or blackmailing you online. Do not send money or personal information and avoid arguing with them. Save screenshots and other evidence, then block and report the account. Tell someone you trust. If there is an immediate threat to your safety, call 112."
    },

    "domestic_violence": {
        "risk": "High",
        "message": "If someone at home is hurting or threatening you, move to a safer place if you can. Stay near a trusted person and keep your phone with you. Avoid confronting the person if it could increase the danger. If you are in immediate danger, call 112."
    },

    "harassment": {
        "risk": "Medium",
        "message": "You may be experiencing harassment. Stay around people you trust and avoid being alone with the person if possible. Save messages, call logs, screenshots, or other evidence. Tell a trusted person and consider reporting the harassment. If the situation becomes dangerous, call 112."
    },

    "physical_danger": {
        "risk": "High",
        "message": "You may be in immediate physical danger. Move to a safe and crowded place now and stay around other people. Do not confront the person if it could put you at greater risk. Call someone you trust and call 112 if you need emergency assistance."
    },

"emergency_help": {
    "risk": "High",
    "message": "🚨 Emergency help needed. Please move to a safe and crowded place if possible. Contact someone you trust. If you are in immediate danger, call 112."
},


    "general_support": {
        "risk": "Low",
        "message": "I am here to support you. Tell me what happened, where you are, and whether you are safe right now. If you are in immediate danger, move to a safe place and call 112."
    }
}



# ==============================
# CHATBOT FUNCTION
# ==============================

def get_response(user_message):

    user_message = user_message.strip()

    # Check if user entered only a numerical value
    if user_message.isdigit():
        return (
            "general_support",
            "Low",
            "🔢 <b>You have entered a numerical value.</b><br>"
            "Please describe your safety concern using words so I can assist you."
        )

    # Your existing ML code starts here
   
    message_vector = vectorizer.transform([user_message])

    # Get prediction probabilities
    probabilities = model.predict_proba(message_vector)[0]

    # Find highest confidence
    max_probability = max(probabilities)

    prediction = model.classes_[probabilities.argmax()]

    # Temporary prediction debug is off

    # If confidence is too low AND prediction is not general support
    if max_probability < 0.30 and prediction != "general_support":
        return (
            "general_support",
            "Low",
            "I couldn't clearly understand the safety concern. "
            "Please tell me what happened in a little more detail."
        )

    risk = responses[prediction]["risk"]
    response = responses[prediction]["message"]

    return prediction, risk, response